Flashl3opard/VibexCode

app/components/Navbar.tsx
This PR updates the Navbar component to use Next.js's built-in <Link> component instead of <button> elements for routing. This ensures proper client-side navigation and improves user experience across both desktop and mobile views.
Imported and used next/link
Replaced Practice, Explore, Dashboard, Login, and Signup buttons with <Link> for both desktop and mobile menus
Maintained existing styles and responsiveness
Retained Start Vibing button with router.push() for custom navigation behavior
=> NavLinks Added, fixed #8

app/components/Navbar.tsx
=> Fixed Navbar Responsiveness, fixes #15

app/components/Navbar.tsx
replaced /dashboard with /Dashboard
fixed #5
=> Changes in navlinks, fixed #5

app/Profile/page.tsx
This PR introduces a fully responsive and interactive Dashboard Page built with React, Tailwind CSS, and Lucide Icons. The layout follows a light-to-dark gradient theme with support for dark mode. It includes three main sections:
fixes https://github.com/Flashl3opard/VibexCode/issues/31
=> Added profile section

app/api/signup/route.ts, app/signup/page.tsx, lib/mongodb.ts, package-lock.json, package.json
=> Added signup route, fixed git #35

app/Profile/page.tsx
=> responsive ui profile, fixes #39

app/components/ProfileSection.tsx, app/signup/page.tsx
=> Changes in Signup page and Profile page

app/login/page.tsx, app/signup/page.tsx
=> Fixed login/signup page responsiveness , #41

app/Explore/page.tsx, app/globals.css, app/layout.tsx, app/page.tsx, package-lock.json, package.json
Added SORA font and implemented animate-on-scroll feature.
=> Changed Font-style to SORA and implemented AOS, fixed #48

app/components/SoundBoard.tsx
Changes in Soundcard
-Add upto 50-200 songs with a scrollable playlist
-Volume and timeline slider
#52
=> Adding soundcard with some changes AGAIN!! #52

app/Profile/page.tsx, app/components/QuestionsSection.tsx, app/topic/[topicName]/page.tsx, lib/questions.ts, models/Categories _temp.ts
=> Added dynamic question section

app/page.tsx
=> Main page create account btn condition applied

lib/firebase.ts
=> api leak haww

app/login/page.tsx, app/signup/page.tsx
=> kar diya yash ka uda diya hua code fix

app/aboutUs/page.tsx, app/components/Footer.tsx
=> added about us page

app/FAQs/page.tsx, app/components/Footer.tsx
FAQ page added and Footer changed :)
=> added faq , #92

app/playground/page.tsx, lib/judge0.ts
=> Playground code editor added using monaco

app/components/EditProfileModal.tsx, app/components/ProfileSection.tsx
=> Added Edit Profile

app/components/Navbar.tsx
=> Fixed notification icon

app/Profile/page.tsx, app/api/judge0/result/[token]/route.ts, app/api/submit/route.ts, app/api/user-submissions/route.ts, app/api/user/mark-solved/route.ts, app/components/HistorySection.tsx, app/playground/page.tsx, app/store/authSlice.ts, app/store/store.ts, models/Submissions.ts
Playground page connected with profile page works correctly
=> fixed api submission, shifting to slice.ts, completed #116

app/components/AuthGuard.tsx
=> Fixed the middleware, causing the issue,completed #132
